//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Bonfire.rc
//
#define IDAPPLY                         3
#define IDD_ABOUTBOX                    100
#define ID_PROJECT_TREE                 101
#define ID_PROJECT_BUTTONS              102
#define IDR_MAINFRAME                   128
#define IDR_BONFIRETYPE                 129
#define IDB_PROJBAR_ICONS               130
#define IDD_OPTIONS_GENERAL_PAGE        130
#define IDD_OPTIONS_EDITOR_PAGE         131
#define IDD_OPTIONS_OUTPUT_PAGE         132
#define IDB_XMLTREE_ICONS               133
#define IDD_PROJECT_ADDFOLDER           134
#define IDR_TOOLBAR_EDIT                135
#define IDR_TOOLBAR_PROJECT             135
#define IDD_OPTIONS                     138
#define IDR_TOOLBAR_FULLSCREEN          141
#define IDR_TOOLBAR_FIND                143
#define IDR_POPUPS                      146
#define IDI_PROJECT                     149
#define IDR_BONFIRE_TYPE                150
#define IDR_BONFIRE_TYPE_OLD            151
#define IDB_MENU_ICONS                  156
#define IDB_TOOLBAR_PROJECT             158
#define IDB_TOOLBAR_FIND                159
#define IDB_TOOLBAR_STANDARD            160
#define IDR_POPUP_FILE                  161
#define IDR_POPUP_PROJECT               162
#define IDR_POPUP_FOLDER                164
#define IDR_POPUP_EDITOR                165
#define IDR_POPUP_XMLELEMENT            166
#define IDR_POPUP_XMLATTRIBUTE          167
#define IDR_POPUP_XMLTEXT               168
#define IDR_POPUP_XMLCOMMENT            169
#define IDB_OUTPUT_ICONS                170
#define IDD_FINDINFILES                 171
#define IDD_GOTO                        175
#define IDD_OPEN_FROM_URL               178
#define IDD_OPTIONS_XMLTREE_PAGE        180
#define IDS_ERROR_PROJECT_FILE          500
#define IDC_BROWSE                      1000
#define IDC_TABS                        1000
#define IDC_FOLDER_PATH                 1001
#define IDC_ADD_FILES                   1002
#define IDC_SUBFOLDERS                  1003
#define IDC_OPT_ADD_SUBFOLDERS          1003
#define IDC_OPT_ADD_FILES               1004
#define IDC_OPTIONS_EDITOR              1005
#define IDC_EDITOROPTION_SAVEDOC        1006
#define IDC_OPTION_SAVEONSWITCH         1006
#define IDC_CHK_SAVE_ON_SWITCH          1006
#define IDC_EDITOROPTION_DRAGEDITING    1007
#define IDC_EDITOROPTION_COLORCODE      1008
#define IDC_OPTIONS_PROJECTEXPLORER     1009
#define IDC_OPTION_CLEAROUTPUT          1010
#define IDC_CHK_CLEAR_OUTPUT            1010
#define IDC_OPTIONS_GENERAL             1011
#define IDC_COLOR_CHOOSE                1011
#define IDC_OPTION_RELOADFILES          1012
#define IDC_OPT_SEARCH_SUBFOLDERS       1012
#define IDC_CHK_RELOAD_MODIFIED         1012
#define IDC_MATCH_WHOLE_WORD            1013
#define IDC_OPT_MATCH_CASE              1014
#define IDC_PRJMGROPTION_DISPLAYPATHS   1015
#define IDC_SEARCH_PATH                 1015
#define IDC_FILE_TYPES                  1016
#define IDC_SEARCH_TEXT                 1017
#define IDC_PRJMGROPTION_DISPLAYPATHS1  1018
#define IDC_CHK_DFP_PROJECTS            1018
#define IDC_PRJMGROPTION_DISPLAYPATHS2  1019
#define IDC_CHK_DFP_FOLDERS             1019
#define IDC_COMBOBOXEX1                 1020
#define IDC_PRJMGROPTION_DISPLAYPATHS3  1021
#define IDC_GOTO_VALUE                  1021
#define IDC_CHK_DFP_FILES               1021
#define IDC_PRJMGROPTION_FOLDERSFIRST   1022
#define IDC_CHK_FOLDERS_FIRST           1022
#define IDC_FIND_TEXT_EX                1023
#define IDC_SEARCH_TEXT_EX              1024
#define IDC_SEARCH_PATH_EX              1025
#define IDC_SEARCH_FILETYPES_EX         1026
#define IDC_EDIT1                       1027
#define IDC_URL                         1027
#define IDC_FONT_SIZE                   1027
#define IDC_FILEEXT                     1027
#define IDC_ADD_FILES_EX                1028
#define IDC_FINDREP_TEXT_EX             1029
#define IDC_LIST_SYNTAX                 1030
#define IDC_EDIT_REPLACE_WITH_EX        1030
#define IDC_CBO_FONT                    1031
#define IDC_CHK_SHOW_XML_COMMENTS       1035
#define IDC_CHK_SHOW_XML_TEXT           1036
#define IDC_CHK_SHOW_XML_ATTRIBUTES     1037
#define IDC_OPTIONS_XMLTREE_FONT        1038
#define IDC_OPTIONS_XMLTREE_FONTSIZE    1039
#define IDC_LIST_FILEEXT                1040
#define IDC_LIST_VIEWS                  1041
#define IDC_MOVE_UP                     1042
#define IDC_MOVE_DOWN                   1043
#define IDC_ADD_EDIT_FILEEXT            1044
#define IDC_DELETE_FILEEXT              1045
#define IDC_CHK_EDIT_XMLTREE            1047
#define IDC_COMBO_HIGHLIGHTING          1048
#define IDS_FILTER_FILES                2000
#define IDS_DEFEXT_PROJECTS             2001
#define IDS_FILTER_PROJECTS             2002
#define IDS_DEFEXT_FILES                2003
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDD_OPTIONS_PROJECTMGR_PAGE     8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDD_OPTIONS_VIEWS_PAGE          8604
#define IDC_EDIT_TEXT                   8605
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDS_EDITOP_TGL_COMMENT          8630
#define IDS_ERROR_VIEWS_FILEEXT_EXISTS  9000
#define IDR_MARGIN_CURSOR               22900
#define IDR_DEFAULT_ACCEL               22901
#define IDB_MARGIN_ICONS                22902
#define ID_EDIT_READONLY                32771
#define ID_FILE_PROPERTIES              32772
#define ID_PROJECT_OPEN                 32776
#define ID_PROJECT_NEW                  32777
#define ID_FILE_SAVEALL                 32779
#define ID_VIEW_PROJECTEXPLORER         32780
#define ID_VIEW_OUTPUTWINDOW            32781
#define ID_VIEW_TAGPROPERTIES           32782
#define ID_VIEW_TOOLBAR_PROJECT         32783
#define ID_PROJECT_SAVE                 32790
#define ID_PROJECT_CLOSE                32791
#define ID_SAVE_ALL                     32793
#define ID_PROJECT_SAVEAS               32797
#define ID_PROJECT_NEWFOLDER            32801
#define ID_PROJECT_NEWFILE              32802
#define ID_EDIT_UPPERCASESELECTION      32806
#define ID_PROJECT_REMOVEFROMPROJECT    32807
#define ID_PROJECT_ADDDIRTOPROJECT      32808
#define ID_PROJECT_ADDFILESTOPROJECT    32809
#define ID_EDIT_LOWERCASESELECTION      32810
#define ID_EDIT_GOTOLINE                32811
#define ID_TOOLS_OPTIONS                32814
#define ID_EDIT_FINDNEXT                32815
#define ID_PROJECT_PROPERTIES           32816
#define ID_VIEW_FULLSCREEN              32817
#define ID_FILE_SHOW                    32820
#define ID_VIEW_TOOLBAR_FIND            32821
#define ID_EDIT_FINDINFILES             32823
#define ID_FILE_MRU_PROJECT1            32845
#define ID_FILE_MRU_PROJECT2            32846
#define ID_FILE_MRU_PROJECT3            32847
#define ID_FILE_MRU_PROJECT4            32848
#define ID_HELP_HOMEPAGE                32849
#define ID_HELP_CONTENTS                32851
#define ID_HELP_SEARCH                  32852
#define ID_FILE_RENAME                  32853
#define ID_FOLDER_RENAME                32854
#define ID_PROJECT_RENAME               32855
#define ID_PROJECT_REFRESHPROJECT       32858
#define ID_PROJECT_REFRESH              32859
#define ID_WINDOW_CLOSEALL              32860
#define ID_FILE_OPENFROMURL             32861
#define ID_TOOLS_LOCATEINEXPLORER       32862
#define ID_TOOLS                        32863
#define ID_TOOLS_OPENDEFAULT            32864
#define ID_FILE_MOVETO_PROJECT2         32865
#define ID_FILE_MOVETO_PROJECT1         32866
#define ID_FILE_MOVETO_PROJECT3         32867
#define ID_EDIT_GOTO                    32867
#define ID_FILE_MOVETO_PROJECT4         32868
#define ID_FILE_MOVETO_PROJECT5         32869
#define ID_FILE_MOVETO_PROJECT6         32870
#define ID_FILE_MOVETO_PROJECT7         32871
#define ID_FILE_MOVETO_PROJECT8         32872
#define ID_ATTRIBUTE_EDIT_NAME          32873
#define ID_ATTRIBUTE_EDIT_VALUE         32874
#define ID_ELEMENT_INSERT_ATTRIBUTE     32880
#define ID_ELEMENT_INSERT_COMMENT       32881
#define ID_ELEMENT_INSERT_TEXT          32882
#define ID_COMMENT_EDIT                 32883
#define ID_ELEMENT_EDIT_NAME            32884
#define ID_ELEMENT_INSERT_ELEMENT       32885
#define ID_TEXTNODE_EDIT                32886
#define ID_ELEMENT_EXPAND               32892
#define ID_ELEMENT_EXPAND_COLLAPSE      32892
#define ID_ELEMENT_EXPANDALL            32894
#define ID_ELEMENT_COLLAPSEALL          32895
#define ID_TOOLS_VALIDATE_FILE          32896
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define ID_INDICATOR_READ               59148
#define ID_INDICATOR_POS                59200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32897
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
